
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#ec2
     url: jdbc:mysql://localhost:3306/yoon
     username: root
     password: 1357qetU!!
# 로컬
#     url: jdbc:mysql://localhost:2222/yoon
#     username: yoon940514
#     password: 1357qetu
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      show_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
logging.level:
  org.hibernate.SQL: debug
  server:
    port: 8081
# org.hibernate.type: trace