
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yoon?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: T=spL6/&6Jx7
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace